// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iftodvqoatrhuzcopbrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdG9kdnFvYXRyaHV6Y29wYnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjYwMjMsImV4cCI6MjA2NzkwMjAyM30.6EuUJbCP23paMI5pcMSKi4ubNjayw3X0djKWoI7Qgf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});